### PR TITLE
Adding a new analysis Notebook

### PR DESCRIPTION
**Pull request by kmpaul**
This new notebook plots the number of session and unique users per day and month.

### CODE REVIEW

**Comment by andersy005** [comment]
Thank you for putting this together, @kmpaul!

This is a neat plot:

jhub

**Comment by kmpaul** [comment]
Thanks, @andersy005!

**Comment by andersy005** [comment]
Another future, interesting question to explore is how casper and cheyenne are used via the JHub. The anomalies/outliers in session durations may also provide insights on which system is more stable. 

Let me know if you are done with the notebook, and I will merge this.

**Review by andersy005 — APPROVED** [review]

**Comment by kmpaul** [comment]
I think those are good questions to ask.  I think it's okay to merge this notebook for now and we can add to it later.  Maybe we can make that a new issue.

I'm also interested in creating a notebook that we can use to create a JupyterHub Status/Statistics page for the https://ncar.github.io/xdev page.  I feel like what I would like for that page would be:

1. real-time status of the JupyterHub via the JH API, and
2. nightly or weekly rendering of statistics plots from the logs (i.e., scrape logs nightly/weekly, run JHub analysis notebook, render notebook as HTML for page, ...)

**Comment by kmpaul** [comment]
Obviously, though, that should be an issue in the https://github.com/NCAR/xdev repo, though.

**Comment by kmpaul** [comment]
@andersy005, I added another notebook with Cheyenne/Casper breakdowns.  Go ahead and merge (or give me write/admin permissions so I can merge myself).

**Comment by andersy005** [comment]
Thank you for your patience, @kmpaul! I've just given you write permissions

**Pull request merged**
